### ISSUE TITLE
Documentation inaccurate in README (sealMessage not exposed in top root exports)

### ISSUE THREAD

**Issue by titanism** [postalsys/mailauth#16]
The README has an example of using `sealMessage` function.  In this example the documentation has incorrectly written the package name as `@postalsys/mailauth` instead of the newly updated name `mailauth`.  Also, the function `sealMessage` is not exported top level, instead it must be required via lib folder.

**Comment by andris9** [comment]
Exposed `sealMessage` in root for v2.3.3, so the documentation is now correct
