### ISSUE TITLE
mailauth returning random EINVALIDKEY DKIM result for Twitter

### ISSUE THREAD

**Issue by titanism** [postalsys/mailauth#30]
Twitter has issue with `mailauth` in that DKIM results have random "invalid public key" results. 

Filing this here and will follow-up if can get more details.

**Comment by andris9** [comment]
I’m on the phone rn so can’t check but are you sure that your custom resolver is returning properly formatted values for TXT records? This quoted structure looks like it is not properly processed. If you use the native resolver, does it return the same value with quotes as well or does it remove quotes?

**Comment by andris9** [comment]
Sorry, typed too slow, saw that you already answered

**Comment by andris9** [comment]
Is such a record even valid? Can’t check while oh phone. Do other services register it as a dkim=pass for the same key 🤔

**Comment by andris9** [comment]
It is definitely not valid. This is a common double quoting mistake. https://mxtoolbox.com/SuperTool.aspx?action=dkim%3atwitter.com%3adkim-201406&run=toolpage

**Comment by andris9** [comment]
Yeah, I see the same, sometimes it returns normal results, sometimes double quoted. Mailauth is working correctly, it’s Twitter that is in the wrong. Super weird.

**Comment by andris9** [comment]
Seems like if the DNS record is returned by `*.r06.twtrdns.net` then it is correct. If by `*.u06.twtrdns.net` then it is invalid.

**Comment by andris9** [comment]
Double quoting is invalid, so there is no need to allow it. In this case it was good it failed and did not pass the quoted value as one of mailauth jobs is to validate the syntax of those records.

**Comment by andris9** [comment]
It’s already morning for me, just about to go to the office 😎
