### ISSUE TITLE
Cloudflare workers support

### ISSUE THREAD

**Issue by schack** [postalsys/mailauth#32]
**Is your feature request related to a problem? Please describe.**
I would like to use mailauth in a Cloudflare Worker, it's currently not possible

**Describe the solution you'd like**
mailauth uses XMLHttpRequest, this is not supported by Cloudflare workers, they use fetch instead

**Comment by andris9** [comment]
Getting mailauth to work with Cloudflare workers would be interesting indeed. Unfortunately, you'd have to rewrite a large part of the module because mailauth uses DNS, etc., which requires access to TCP and UDP. As far as I know, this is not possible with Cloudflare workers.
