### ISSUE TITLE
No RR returned if default mechanish is missing

### ISSUE THREAD

**Issue by schack** [postalsys/mailauth#35]
**Describe the bug**
The RR field is not returned for SPF records where the default mechanism is missing

**To Reproduce**

mailauth spf -f bellcom.dk -i 1.2.3.4
{
  "domain": "bellcom.dk",
  "client-ip": "1.2.3.4",
  "envelope-from": "postmaster@bellcom.dk",
  "status": {
    "result": "neutral",
    "comment": "STL-R7N4H9RQF6: 1.2.3.4 is neither permitted nor denied by domain of postmaster@bellcom.dk",
    "smtp": {
      "mailfrom": "postmaster@bellcom.dk"
    }
  },
  "header": "Received-SPF: neutral (STL-R7N4H9RQF6: 1.2.3.4 is neither permitted nor denied by domain of postmaster@bellcom.dk) client-ip=1.2.3.4;",
  "info": "spf=neutral (STL-R7N4H9RQF6: 1.2.3.4 is neither permitted nor denied by domain of postmaster@bellcom.dk) smtp.mailfrom=postmaster@bellcom.dk"
}

However:
dig +short bellcom.dk txt
"v=spf1 include:_spf.bellcom.dk"
"google-site-verification: mrYNF5E8kEkNacSV-zrITF03H7FSh6-qTTki86F6k84"

**Expected behavior**
I think to remember the default mechanish is ?all (neutral), so while the record is sort of meaningless it is valid, and it would be nice if the RR field in the result was set.

**Comment by andris9** [comment]
Fixed with [v4.3.3](https://github.com/postalsys/mailauth/releases/tag/v4.3.3)

<img width="1200" alt="Screenshot 2023-04-13 at 10 53 32" src="https://user-images.githubusercontent.com/132242/231692130-5760c6c5-cc4b-47cd-9d61-8b09697c25f7.png">

**Comment by schack** [comment]
Thanks again :-)
