### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by schack** [postalsys/mailauth#37]
**Describe the bug**
Not really bug, just a question, and I couldn't find another way to contact you.
Is there a way to configure DNS timeout values?

From time to time, I detect invalid SPF records, and if I try again, the issue is gone.

DNS timeouts are the only reason I can think of.

**Comment by schack** [comment]
Thanks, sadly, I'm not sure how to implement that :-(
Pretty new in the js world

**Comment by andris9** [comment]
Does the SPF query end with a temperror state? This is what is supposed to happen on DNS timeouts etc. To handle it either retry the request or improve your DNS stack. Increasing allowed time is not the correct approach - with UDP if you already need to wait you are probably not going to get the answer anyway. If the result is something else than temperror then it might be an issue on the Mailauth side.
