### ISSUE TITLE
Assets for 4.6.1 release?

### ISSUE THREAD

**Issue by luckman212** [postalsys/mailauth#53]
Hi, I saw a 4.6.1 release was published :tada: but the assets seem to be missing. For example, the [`mailauth-arm.pkg`](https://github.com/postalsys/mailauth/releases/latest/download/mailauth-arm.pkg) referenced in the [Install docs](https://github.com/postalsys/mailauth/blob/master/cli.md#installation). Is there some CI script that needs to run to generate these?

**Comment by andris9** [comment]
Oh, you’re correct, I forgot to run the release script that builds and signs the packages. I’ll do this by tomorrow. For now I marked this release as pre-release, so that download links would point to the previous release.

**Comment by andris9** [comment]
Released v4.6.2 with built assets

**Comment by luckman212** [comment]
@andris9 Sorry to bug you but I think the same thing just happened for the 4.6.9 release...

**Comment by andris9** [comment]
Oh, yeah, forgot again. Built and published missing assets.

**Comment by luckman212** [comment]
Hello @andris9 👋 

I believe this happened again (assets missing) for [4.9.0](https://github.com/postalsys/mailauth/releases/tag/v4.9.0). Sorry to bother...

**Comment by andris9** [comment]
Well, yeah, I can not automate the process because of Mac OS executable signing, I only have the keys in my personal machine, do not want to add these to Github
