### ISSUE TITLE
Performance issue with `ensureLinebreaks` and `writeAsync` functions

### ISSUE THREAD

**Issue by titanism** [postalsys/mailauth#73]
Not sure if this could be rewritten or optimized, but this is the largest bottleneck in our source code from `cpupro` and `v8-profiler-next` monitoring:

<https://github.com/postalsys/mailauth/blob/3c47729fc23cc18825d7b33fe5570f30372e9b91/lib/dkim/message-parser.js#L112-L126>

**Comment by andris9** [comment]
`ensureLinebreaks` is a generator function, so the result does not really surprise me (see [this post](https://dev.to/somedood/i-was-wrong-about-array-methods-and-generators-2ig9) about generator performance). It would probably be faster when using an alternative approach but I really like how the current design hides away the complexity of the operation.

**Comment by andris9** [comment]
Well, unfortunately, I'm extremely busy with other stuff, and the performance of this method has not been an issue at all for us, so this issue is not a priority at all. I added a label to prevent auto-closing this issue, though.
